### ISSUE TITLE
[IMPROVE] when slider value is hidden, its label is partly covered

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#49] opened 2018-11-01 07:59 UTC
Font Size: 16px (standard size) 
![grafik](https://user-images.githubusercontent.com/43702087/47839581-7f559600-ddb3-11e8-898c-b19a584945ee.png)

Font Size: 15px 
![grafik](https://user-images.githubusercontent.com/43702087/47839705-f1c67600-ddb3-11e8-9e21-41589fde0ba1.png)

Font Size: 24px
![grafik](https://user-images.githubusercontent.com/43702087/47839728-0c005400-ddb4-11e8-8bf0-2e226d915fc2.png)

As the slider is automatically sized according the Font Size, the space between label and slider varies (see pics above)
Suggestion: Can you vertical-align the slider itself at the bottom of its frame? So it wouldn't cover the descenders of letters in the label, without increasing the space at the bottom.

**Comment by TimSusa** [comment] 2018-11-01 19:01
I am not very proud of the code, that manages this, because the problem is very nasty, complex and evil and I have no clue at the moment, how to make that really cool. Anyhow, I will take a look at it.

**Comment by alectroniq** [comment] 2018-11-02 09:42
example preset:
[horizontal slider example.zip](https://github.com/TimSusa/midi-sliders/files/2541899/horizontal.slider.example.zip)

**Comment by alectroniq** [comment] 2018-11-02 16:41
It would also be fine, if the value appears right on the slider's track, just as it does on the horziontal slider. This could mean, that the slider itself doesn't need to be resized for the value. 
But generally this is not super urgent right now.

**Comment by alectroniq** [comment] 2018-11-25 15:54
test: okay now

**Comment by alectroniq** [comment] 2018-11-25 16:00
Unfortunately not solved in v0.14.0:
![49](https://user-images.githubusercontent.com/43702087/48981277-99914400-f0d3-11e8-9ac3-522e25597ca3.JPG)

**Comment by TimSusa** [comment] 2019-01-26 13:44
should be fixed

**Closed by TimSusa** 2019-01-26 13:44 UTC
Labels: enhancement
