### ISSUE TITLE
[BUG] settings: color picker states not correct (transparency)

### ISSUE THREAD

**Issue by alectroniq** [TimSusa/midi-sliders#40] opened 2018-10-23 15:09 UTC
in settings mode: when opening the color picker of an element, it doesn't show the exact color settings, that it already has. especially the transparency settings shows another value.

**Comment by TimSusa** [comment] 2018-10-23 21:15
That sounds strange to me, because I took a lot of effort to handle this. Are you able to reproduce this? If yes, only webapp or electron app and webapp?

**Comment by alectroniq** [comment] 2018-10-24 07:45
https://we.tl/t-czLw6BmSYD
video in german. sorry for the blurriness!

**Comment by TimSusa** [comment] 2018-10-27 12:48
Fixed with: https://github.com/TimSusa/midi-sliders/commit/2145134234228e0913619f7d5eabc6c92aab49ce

**Closed by TimSusa** 2018-10-27 12:48 UTC
Labels: bug

**Comment by alectroniq** [comment] 2018-10-29 13:51
test positive

**Comment by alectroniq** [comment] 2018-10-29 13:51
test positive (chrome)
